name: RSS Convert Action
description: Filters and converts RSS feeds

runs:
  using: composite
  steps:
    - name: Update feeds
      run: |
        HUSKY=0 yarn --cwd ${{ github.action_path }} install --production 
        node ${{ github.action_path }}/bin/index.js
      shell: bash
    - name: Commit changes
      run: |
        git config user.name "rssconv"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "update: ${timestamp}" || exit 0
        git push
      shell: bash
